### ISSUE TITLE
High CPU use after jobber test

### ISSUE THREAD

**Issue by swalladge** [dshearer/jobber#301]
Running jobber 1.4.3 on archlinux, built from [pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jobber).

Normal execution is fine, but when I run `jobber test <any job>`, cpu use of the jobberrunner for my user leaps to around 100%. i run `jobber test ...` again, and cpu jumps to 200%, and so on up to about 450% (this is as reported by htop; I'm assuming it's because multi cores?). Some kind of resource leak?

**Comment by D-K-E** [comment]
Same issue, I downloaded debian release. `jobber -v` outputs `Jobber 1.4.3`

**Comment by dshearer** [comment]
Oh man... hashtag lame.

**Comment by MCOfficer** [comment]
I'm also seeing constantly high CPU load without any jobs running. Just to show off the severity, this is my netdata CPU graph:
![image](https://user-images.githubusercontent.com/22377202/83443867-bfc33d00-a44a-11ea-9637-87961ff05676.png)

- The drop at 20:55:20 is a `systemctl stop jobber`
- The short peak at 20:57:17 a `systemctl start jobber`
- At 20:57:40 i `jobber test` a resource-intensive job (7z compression)
- At 20:48:40 the job finished, but a certain amount of CPU load remains.

I thought that there were a lot of jobber processes, but the number was the same after a clean service start and after the test run (35).

**Comment by dshearer** [comment]
Fixed in v1.4.4.  Sorry for my incompetence.

**Comment by swalladge** [comment]
@dshearer, thanks for the quick fix! 

> Sorry for my incompetence.

No not at all! Thank you for building an awesome tool. :+1: :+1:

**Comment by PegasisForever** [comment]
The [docker version](https://hub.docker.com/_/jobber) of jobber is not updated and still have this bug.

**Comment by MCOfficer** [comment]
You can open an issue over at https://github.com/dshearer/jobber-docker
